---
title: "Project"
output: pdf_document
---
```{r,import data}
mydat <- read.csv("~/GitHub/Data-Challenge-2019/data/Data_wide_ENG.csv")
```
\
```{r test}
for (i in 1:95) {
  i <- i*71
  if(i == 71){
    print(i)
  } else if (i == 71 * 2){
    print(i)
  }
}
```
\
```{r forecastExit}
timeseries.predict <- function(data, variable, forecast.time) {
  predictions <- NULL
  Indus <- NULL
  Geo <- NULL
  if (variable == "Exit") {
    for (i in 1:95) {
      newhope <- data$Exit[((i-1)*71+1):(i*71)]
      newhope <- ts(newhope,frequency = 4)
      newhope <- na.omit(newhope)
      myhope <- ts(newhope,frequency = 4)
      model1 <- auto.arima(myhope)
      a <- forecast(model1,h=forecast.time)
      con <- c(round(a$mean))
      predictions <- rbind(predictions,con)
      Indus <- c(Indus,as.character(data$NAICS_Codes[(71*i)]))
      Geo <- c(Geo,as.character(data$Geography[(71*i)]))
    }
    row.names(predictions) <- NULL
    colname <- NULL
    for (j in 1:forecast.time) {
      colname <- c(colname, paste("Q", sep = "", as.character(j)))
    }
    colnames(predictions) <- colname
    prediction1 <- as.data.frame(predictions)
    prediction1$Geography <- Geo
    prediction1$Industry <- Indus
    prediction <- prediction1[, c(forecast.time + 1, forecast.time + 2, 1:forecast.time)]
    write.csv(prediction, file = "prediction_exit.csv")
    
  } else if (variable == "Entry") {
    for (i in 1:95) {
      newhope <- data$Entry[((i-1)*71+1):(i*71)]
      newhope <- ts(newhope,frequency = 4)
      newhope <- na.omit(newhope)
      myhope <- ts(newhope,frequency = 4)
      model1 <- auto.arima(myhope)
      a <- forecast(model1,h=forecast.time)
      con <- c(round(a$mean))
      predictions <- rbind(predictions,con)
      Indus <- c(Indus,as.character(data$NAICS_Codes[(71*i)]))
      Geo <- c(Geo,as.character(data$Geography[(71*i)]))
    }
    row.names(predictions) <- NULL
    colname <- NULL
    for (j in 1:forecast.time) {
      colname <- c(colname, paste("Q", sep = "", as.character(j)))
    }
    colnames(predictions) <- colname
    prediction1 <- as.data.frame(predictions)
    prediction1$Geography <- Geo
    prediction1$Industry <- Indus
    prediction <- prediction1[, c(forecast.time + 1, forecast.time + 2, 1:forecast.time)]
    write.csv(prediction, file = "prediction_entry.csv")
    
  } else if (variable == "Opening") {
    for (i in 1:95) {
      newhope <- data$Opening[((i-1)*71+1):(i*71)]
      newhope <- ts(newhope,frequency = 4)
      newhope <- na.omit(newhope)
      myhope <- ts(newhope,frequency = 4)
      model1 <- auto.arima(myhope)
      a <- forecast(model1,h=forecast.time)
      con <- c(round(a$mean))
      predictions <- rbind(predictions,con)
      Indus <- c(Indus,as.character(data$NAICS_Codes[(71*i)]))
      Geo <- c(Geo,as.character(data$Geography[(71*i)]))
    }
    row.names(predictions) <- NULL
    colname <- NULL
    for (j in 1:forecast.time) {
      colname <- c(colname, paste("Q", sep = "", as.character(j)))
    }
    colnames(predictions) <- colname
    prediction1 <- as.data.frame(predictions)
    prediction1$Geography <- Geo
    prediction1$Industry <- Indus
    prediction <- prediction1[, c(forecast.time + 1, forecast.time + 2, 1:forecast.time)]
    write.csv(prediction, file = "prediction_opening.csv")
    
  } else if (variable == "Closing") {
    for (i in 1:95) {
      newhope <- data$Closing[((i-1)*71+1):(i*71)]
      newhope <- ts(newhope,frequency = 4)
      newhope <- na.omit(newhope)
      myhope <- ts(newhope,frequency = 4)
      model1 <- auto.arima(myhope)
      a <- forecast(model1,h=forecast.time)
      con <- c(round(a$mean))
      predictions <- rbind(predictions,con)
      Indus <- c(Indus,as.character(data$NAICS_Codes[(71*i)]))
      Geo <- c(Geo,as.character(data$Geography[(71*i)]))
    }
    row.names(predictions) <- NULL
    colname <- NULL
    for (j in 1:forecast.time) {
      colname <- c(colname, paste("Q", sep = "", as.character(j)))
    }
    colnames(predictions) <- colname
    prediction1 <- as.data.frame(predictions)
    prediction1$Geography <- Geo
    prediction1$Industry <- Indus
    prediction <- prediction1[, c(forecast.time + 1, forecast.time + 2, 1:forecast.time)]
    write.csv(prediction, file = "prediction_closing.csv")
    
  } else if (variable == "Active") {
    for (i in 1:95) {
      newhope <- data$Active[((i-1)*71+1):(i*71)]
      newhope <- ts(newhope,frequency = 4)
      newhope <- na.omit(newhope)
      myhope <- ts(newhope,frequency = 4)
      model1 <- auto.arima(myhope)
      a <- forecast(model1,h=forecast.time)
      con <- c(round(a$mean))
      predictions <- rbind(predictions,con)
      Indus <- c(Indus,as.character(data$NAICS_Codes[(71*i)]))
      Geo <- c(Geo,as.character(data$Geography[(71*i)]))
    }
    row.names(predictions) <- NULL
    colname <- NULL
    for (j in 1:forecast.time) {
      colname <- c(colname, paste("Q", sep = "", as.character(j)))
    }
    colnames(predictions) <- colname
    prediction1 <- as.data.frame(predictions)
    prediction1$Geography <- Geo
    prediction1$Industry <- Indus
    prediction <- prediction1[, c(forecast.time + 1, forecast.time + 2, 1:forecast.time)]
    write.csv(prediction, file = "prediction_active.csv")
    
  } else {
    print("Usage: variable = {Exit, Entry, Opening, Closing, Active}")
  }
}

timeseries.predict(mydat, variable = "Exit", forecast.time = 4)
timeseries.predict(mydat, variable = "Entry", forecast.time = 4)
timeseries.predict(mydat, variable = "Opening", forecast.time = 4)
timeseries.predict(mydat, variable = "Closing", forecast.time = 4)
timeseries.predict(mydat, variable = "Active", forecast.time = 4)
```
\
```{r, foreEntry}
predictions <- NULL
Indus <- NULL
Geo <- NULL
for (i in 1:95) {
newhope <- data$Entry[((i-1)*71+1):(i*71)]
newhope <- ts(newhope,frequency = 4)
newhope <- na.omit(newhope)
myhope <- ts(newhope,frequency = 4)
model1 <- auto.arima(myhope)
a <- forecast(model1,h=5)
con <- c(a$mean)
predictions <- rbind(predictions,con)
Indus <- c(Indus,as.character(data$NAICS_Codes[(71*i)]))
Geo <- c(Geo,as.character(data$Geography[(71*i)]))
}
row.names(predictions) <- NULL
colnames(predictions) <- c("Q1", "Q2", "Q3", "Q4","Q5")
prediction2 <- as.data.frame(predictions)
prediction2$Geography <- Geo
prediction2$Industry <- Indus
```
\
```{r,ratio}
Indus <- prediction1$Industry
Pr <- prediction1$Province
ratio <- prediction2[,1:5]/prediction1[,1:5]
prediction_for_ratio <- as.data.frame(ratio)
prediction_for_ratio$Geography <- Geo
prediction_for_ratio$Industry <- Indus
```





